### ISSUE TITLE
Error when trying to run droidstatx [on MacBook]

### ISSUE THREAD

**Issue by poldenais** [integrity-sa/droidstatx#4]
HI,
I'm trying to run this on a MacBook and get the following error below. Apologies if I missed anything here.

*************************************************************************************************

Poldenais-MacBook-Air:droidstatx-master poldenais$ python droidstatx.py --apk base.apk

 _____                _      _                            _    _ 
(____ \              (_)    | |       _           _      \ \  / /
 _   \ \  ____  ___   _   _ | |  ___ | |_   ____ | |_  ___\ \/ / 
| |   | |/ ___)/ _ \ | | / || | /___)|  _) / _  ||  _)(___))  (  
| |__/ /| |   | |_| || |( (_| ||___ || |__( ( | || |__    / /\ \ 
|_____/ |_|    \___/ |_| \____|(___/  \___)\_||_| \___)  /_/  \_\ v0.3 
       Android Applications Security Analyser, Xmind Generator 
       Created by @clviper

[-]Parsing APK
[-]Baksmaling DEX files
Traceback (most recent call last):
  File "droidstatx.py", line 23, in <module>
    a = App(args.apk[0])
  File "/Users/poldenais/Desktop/MobileSecurity/droidstatx-master/App.py", line 68, in __init__
    self.bakmali(apkFile)
  File "/Users/poldenais/Desktop/MobileSecurity/droidstatx-master/App.py", line 545, in bakmali
    self.smaliChecks = SmaliChecks(self.baksmaliPaths)
  File "/Users/poldenais/Desktop/MobileSecurity/droidstatx-master/SmaliChecks.py", line 36, in __init__
    self.checkWebviewSSLErrorBypass()
  File "/Users/poldenais/Desktop/MobileSecurity/droidstatx-master/SmaliChecks.py", line 348, in checkWebviewSSLErrorBypass
    webviewErrorBypassLocations = self.checkForExistenceInFolder("Landroid\/webkit\/SslErrorHandler;->proceed\(\)V",self.getSmaliPaths())
  File "/Users/poldenais/Desktop/MobileSecurity/droidstatx-master/SmaliChecks.py", line 65, in checkForExistenceInFolder
    grep = Popen(command, stdout=PIPE)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by clviper** [comment]
Hi @poldenais . You will need gnu grep installed, since the grep in OSX does not have the same parameters as gnu. Just guarantee that the command is available system wide via ggrep (Think is the default behavior when installed via brew)

**Comment by clviper** [comment]
Hi @poldenais . Can you please confirm so I can close this issue? Thanks

**Comment by poldenais** [comment]
Hi Claudio, Yes please do close this. I installed grep and it works now, apologies for the delay.

**Comment by clviper** [comment]
No problem @poldenais . Glad you got it working.
